#!/usr/bin/env python3
"""
compute-canon-hashes.py — Generate or verify 99-meta/canon-hashes.json.

Source of truth: AEC §"Distribution canonique" (rules-agent-exit-contract.md).

For each canon entry:
  canon_sha256        — SHA-256 of full canon file (frontmatter included)
  distribution_sha256 — SHA-256 of canon body (YAML frontmatter stripped)

Modes:
  --check   read 99-meta/canon-hashes.json, recompute, fail on drift (CI gate)
  --write   recompute and overwrite 99-meta/canon-hashes.json (signed commit)
  --print   print computed hashes to stdout (no file IO)
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
HASHES_PATH = REPO_ROOT / "99-meta" / "canon-hashes.json"

# Canon registry — extend here when a new canon distribution is added.
CANONS: dict[str, dict] = {
    "aec": {
        "name": "Agent Exit Contract",
        "canon_path": "ledger/rules/rules-agent-exit-contract.md",
        "version": "1.0.1",
        "consumers": [
            {"repo": "ak125/automecanik-wiki", "path": "_meta/agent-exit-contract.md"},
            {"repo": "ak125/automecanik-raw", "path": "agent-exit-contract.md"},
            {"repo": "ak125/nestjs-remix-monorepo", "path": ".claude/canon-mirrors/agent-exit-contract.md"},
            {"repo": "ak125/nestjs-remix-monorepo", "path": "workspaces/seo-batch/.claude/canon-mirrors/agent-exit-contract.md"},
            {"repo": "ak125/nestjs-remix-monorepo", "path": "workspaces/marketing/.claude/canon-mirrors/agent-exit-contract.md"},
        ],
    },
    "marketing_voice": {
        "name": "Marketing Brand Voice",
        "canon_path": "ledger/rules/rules-marketing-voice.md",
        "version": "1.0.1",
        "consumers": [
            {"repo": "ak125/nestjs-remix-monorepo", "path": ".claude/canon-mirrors/marketing-voice.md"},
            {"repo": "ak125/nestjs-remix-monorepo", "path": "workspaces/marketing/.claude/canon-mirrors/marketing-voice.md"},
        ],
    },
}

FRONTMATTER_RE = re.compile(r"^---\n.*?\n---\n*", re.DOTALL)


def strip_frontmatter(text: str) -> str:
    return FRONTMATTER_RE.sub("", text, count=1)


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def compute() -> dict:
    canons_out: dict[str, dict] = {}
    for key, meta in CANONS.items():
        canon_file = REPO_ROOT / meta["canon_path"]
        if not canon_file.exists():
            sys.exit(f"ERROR: canon file missing: {meta['canon_path']}")
        text = canon_file.read_text(encoding="utf-8")
        canons_out[key] = {
            "name": meta["name"],
            "canon_path": meta["canon_path"],
            "canon_sha256": sha256_text(text),
            "distribution_sha256": sha256_text(strip_frontmatter(text)),
            "version": meta["version"],
            "consumers": meta["consumers"],
        }
    return {
        "$comment": "Generated by _scripts/compute-canon-hashes.py — do not edit by hand.",
        "version": "1.0.0",
        "updated": date.today().isoformat(),
        "canons": canons_out,
    }


def write_json(data: dict) -> None:
    HASHES_PATH.parent.mkdir(parents=True, exist_ok=True)
    HASHES_PATH.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--print", action="store_true")
    args = ap.parse_args()

    computed = compute()

    if args.print:
        print(json.dumps(computed, indent=2, ensure_ascii=False))
        return 0

    if args.write:
        write_json(computed)
        print(f"WROTE {HASHES_PATH.relative_to(REPO_ROOT)}")
        return 0

    # --check
    if not HASHES_PATH.exists():
        sys.exit(f"ERROR: {HASHES_PATH.relative_to(REPO_ROOT)} missing — run with --write")
    on_disk = json.loads(HASHES_PATH.read_text(encoding="utf-8"))
    # Ignore `updated` field for drift detection — only hashes matter.
    drift = []
    for key, meta in computed["canons"].items():
        disk = on_disk.get("canons", {}).get(key)
        if not disk:
            drift.append(f"  + {key}: missing in canon-hashes.json")
            continue
        if disk["canon_sha256"] != meta["canon_sha256"]:
            drift.append(
                f"  ! {key}.canon_sha256 drift: disk={disk['canon_sha256'][:12]}… "
                f"computed={meta['canon_sha256'][:12]}…"
            )
        if disk["distribution_sha256"] != meta["distribution_sha256"]:
            drift.append(
                f"  ! {key}.distribution_sha256 drift: disk={disk['distribution_sha256'][:12]}… "
                f"computed={meta['distribution_sha256'][:12]}…"
            )
    if drift:
        print("DRIFT detected — re-run `_scripts/compute-canon-hashes.py --write`:")
        print("\n".join(drift))
        return 1
    print("OK — canon-hashes.json in sync with canon files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
