#!/usr/bin/env bash
# cron-sync-moc-decisions.sh — Wrapper VPS DEV pour invocation cron quotidienne
# de sync_moc_decisions.py.
#
# ## Pattern canonique (ADR-015 + vault-canon-read-only-on-gha)
#   1. Pull origin main
#   2. Run sync_moc_decisions --write sur branche temp
#   3. Si diff : commit signé G3, push branche, ouvre auto-PR
#   4. Si no-op : exit 0 silencieux
#
# AUCUN push direct main. Toutes les écritures auto-PR signées.
#
# ## Phase A (PR-3 — observation 3-7j)
#   Ce wrapper produit des auto-PRs visibles dans `gh pr list` du vault. Le
#   reviewer humain merge si OK. Une fois le pattern stabilisé (PR-4) :
#       - check-mode wired dans ci-vault-gate.sh
#       - cron passe en --check + alerte si drift
#
# ## Variables d'environnement attendues
#   GH_TOKEN          : token avec write:repo sur ak125/governance-vault
#   GIT_USER_NAME     : "Deploy Bot" (auto-PR author)
#   GIT_USER_EMAIL    : automecanik.seo@gmail.com
#   GPG_KEY_ID        : clé G3 pour signed commit (déjà loadée dans agent)
#
# ## Usage manuel (debugging)
#   bash _scripts/cron-sync-moc-decisions.sh        # observe diff + auto-PR
#   bash _scripts/cron-sync-moc-decisions.sh dry    # dry-run, no PR
set -euo pipefail

VAULT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$VAULT_ROOT"

DRY_RUN="${1:-}"
TODAY="$(date -u +%Y-%m-%d)"
BRANCH="govvault/cron-moc-sync-${TODAY}"

# 1. Sync main
git fetch origin main --quiet
git checkout main --quiet
git reset --hard origin/main --quiet

# 2. Run the generator on a temp branch
git checkout -b "$BRANCH" --quiet 2>/dev/null || git checkout "$BRANCH" --quiet

if [[ "$DRY_RUN" == "dry" ]]; then
  python3 _scripts/sync_moc_decisions.py --dry-run
  exit 0
fi

python3 _scripts/sync_moc_decisions.py --write

# 3. Detect diff
if git diff --quiet ops/moc/MOC-Decisions.md; then
  echo "OK: no diff today, no PR opened"
  git checkout main --quiet
  git branch -D "$BRANCH" --quiet
  exit 0
fi

# 4. Commit signed + push + auto-PR
git add ops/moc/MOC-Decisions.md
git commit -S -m "$(cat <<EOF
chore(moc): auto-sync MOC-Decisions canonical index — ${TODAY}

Generated by _scripts/sync_moc_decisions.py from ADR frontmatters.
Section between markers \`<!-- AUTO-GENERATED:moc-decisions-canonical-index ... -->\`.

Self-review verdict: APPROVE
EOF
)"

git push -u origin "$BRANCH" --quiet

# Defense vs orphan branch (PR-3 review [I2]) : si gh pr create échoue
# (token expired, label missing, network), nettoyer la branche distante
# pour ne pas polluer le remote sur runs successifs. Conforme au critère
# PR-4 « 0 issue infra-fail non résolue ».
if ! gh pr create --repo ak125/governance-vault \
  --title "chore(moc): auto-sync MOC-Decisions canonical index — ${TODAY}" \
  --body "Auto-PR par cron VPS DEV \`cron-sync-moc-decisions.sh\` (PR-3 observation phase). Diff entre markers \`<!-- AUTO-GENERATED:moc-decisions-canonical-index ... -->\`. Reviewer humain valide ou ferme.

Self-review verdict: APPROVE" \
  --label "auto"; then
  echo "::warning:: gh pr create failed — cleaning up orphan branch $BRANCH" >&2
  git push origin --delete "$BRANCH" --quiet 2>&1 | tail -1
  git checkout main --quiet
  exit 1
fi

git checkout main --quiet
echo "OK: auto-PR opened on branch $BRANCH"
