#!/usr/bin/env bash
# cron-sync-canon-mirrors.sh — Wrapper VPS DEV pour invocation cron quotidienne
# de sync_canon_mirrors.py (ADR-061 §3).
#
# ## Pattern canonique (ADR-015 + ADR-061 §3 canon mirrors read-only)
#   1. cd monorepo, pull origin main
#   2. Run sync_canon_mirrors --write sur branche temp
#   3. Si diff : commit signé G3, push branche, ouvre auto-PR monorepo
#   4. Si no-op : exit 0 silencieux
#
# AUCUN push direct main monorepo. Toutes les écritures auto-PR.
#
# ## Différences vs cron-sync-moc-decisions.sh
#   - Sync cross-repo (vault → monorepo) au lieu d'intra-vault.
#   - Le commit + PR se font côté monorepo, pas vault.
#   - La logique sync est en Python (multi-targets, hash-aware).
#
# ## Phase A (observation 3-7j)
#   Auto-PRs visibles dans `gh pr list --repo ak125/nestjs-remix-monorepo`.
#   Reviewer humain merge si OK. Une fois stabilisé :
#       - check-mode wired dans CI monorepo (canon-mirrors-verify)
#       - cron passe en --check + alerte si drift
#
# ## Variables d'environnement attendues
#   GH_TOKEN          : token avec write:repo sur ak125/nestjs-remix-monorepo
#   GIT_USER_NAME     : "Deploy Bot" (auto-PR author)
#   GIT_USER_EMAIL    : automecanik.seo@gmail.com
#   GPG_KEY_ID        : clé G3 pour signed commit (déjà loadée dans agent)
#
# ## Usage manuel (debugging)
#   bash _scripts/cron-sync-canon-mirrors.sh        # observe diff + auto-PR
#   bash _scripts/cron-sync-canon-mirrors.sh dry    # dry-run, no PR

set -euo pipefail

VAULT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MONOREPO_ROOT="${MONOREPO_ROOT:-/opt/automecanik/app}"

DRY_RUN="${1:-}"
TODAY="$(date -u +%Y-%m-%d)"
TIMESTAMP="$(date -u +%Y-%m-%dT%H%M%SZ)"
BRANCH="govvault/cron-sync-canon-mirrors-${TIMESTAMP}"

if [[ ! -d "$MONOREPO_ROOT" ]]; then
  echo "Error: monorepo not found at $MONOREPO_ROOT" >&2
  exit 2
fi

# 1. Dry-run mode : preview seul (pas de checkout, pas de PR)
if [[ "$DRY_RUN" == "dry" ]]; then
  python3 "$VAULT_ROOT/_scripts/sync_canon_mirrors.py" --dry-run --monorepo "$MONOREPO_ROOT"
  exit 0
fi

# 2. Sync monorepo main
cd "$MONOREPO_ROOT"
git fetch origin main --quiet
git checkout main --quiet
git reset --hard origin/main --quiet

# 3. Run le sync sur branche temp monorepo
git checkout -b "$BRANCH" --quiet 2>/dev/null || git checkout "$BRANCH" --quiet

python3 "$VAULT_ROOT/_scripts/sync_canon_mirrors.py" --write --monorepo "$MONOREPO_ROOT"

# 4. Detect diff
if git diff --quiet; then
  echo "OK: no canon mirror drift today, no PR opened"
  git checkout main --quiet
  git branch -D "$BRANCH" --quiet
  exit 0
fi

# 5. Commit signed + push + auto-PR monorepo
git add .claude/canon-mirrors/ workspaces/*/.claude/canon-mirrors/ 2>/dev/null || true
git commit -S -m "$(cat <<EOF
chore(canon-mirrors): auto-sync from vault — ${TODAY}

Generated by governance-vault/_scripts/sync_canon_mirrors.py via cron-sync-canon-mirrors.sh.
Source: ak125/governance-vault 99-meta/canon-hashes.json manifest.

ADR-061 §3 canon mirrors are read-only mirrors. Edits must come from vault canon source.
EOF
)"

git push -u origin "$BRANCH" --quiet

# Defense vs orphan branch : si gh pr create échoue, cleanup branche distante.
if ! gh pr create --repo ak125/nestjs-remix-monorepo \
  --base main \
  --head "$BRANCH" \
  --title "chore(canon-mirrors): auto-sync from vault — ${TODAY}" \
  --body "Auto-PR par cron VPS DEV \`cron-sync-canon-mirrors.sh\` (ADR-061 §3).

Sync \`.claude/canon-mirrors/\` + \`workspaces/*/.claude/canon-mirrors/\` depuis le canon source vault.

Source of truth : \`governance-vault/99-meta/canon-hashes.json\` manifest + \`ledger/rules/rules-*.md\` canon files.

Reviewer humain valide ou ferme." \
  --label "auto"; then
  echo "::warning:: gh pr create failed — cleaning up orphan branch $BRANCH" >&2
  git push origin --delete "$BRANCH" --quiet 2>&1 | tail -1
  git checkout main --quiet
  exit 1
fi

git checkout main --quiet
echo "OK: auto-PR opened on branch $BRANCH"
